development:
  access_key_id: AKIAJMRBJR4EDDFFAGQQ
  secret_access_key: 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
production:
  access_key_id: AKIAJMRBJR4EDDFFAGQQ
  secret_access_key: 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
